server.port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate:
      SQL: DEBUG

voicemap:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:voicemap;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool-name: voicemap-hikari-pool
  ai:
    instructions:
      agent: you are kind.
      document: you are kind.
      chat: you are kind.
      context-summarizer: you are kind.

auth:
  google:
    client-id: test

jwt:
  secret-key: secretsecretsecretsecretsecretsecretsecretsecret
  access-token-expire-duration: 1h
  refresh-token-expire-duration: 7d

gemini:
  api-key: apikey
  urls:
    agent-web-socket-url: wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContent
    document-api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    chat-api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
  models:
    agent-model: models/gemini-2.5-flash-native-audio-preview-12-2025
    document-model: gemini-2.5-flash
    chat-model: gemini-2.5-flash
---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
