server.port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate:
      SQL: DEBUG

voicemap:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:voicemap;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool-name: voicemap-hikari-pool


auth:
  google:
    client-id: test

jwt:
  secret-key: secretsecretsecretsecretsecretsecretsecretsecret
  access-token-expire-duration: 1h
  refresh-token-expire-duration: 7d

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

voicemap:
  datasource:
    driver-class-name: # TODO: add properties
    jdbc-url:
    username:
    password:
    pool-name: voicemap-hikari-pool
